-keep class com.baseflow.geolocator.** { *; }
-keep class com.baseflow.googleapiavailability.** { *; }
-keep class com.baseflow.permissionhandler.** { *; }
-dontwarn com.baseflow.geolocator.**
-dontwarn com.baseflow.googleapiavailability.**
-dontwarn com.baseflow.permissionhandler.** 